# Generated by Django 4.2.25 on 2026-03-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='favorite_scent',
            field=models.CharField(choices=[('woody', 'Woody & Earthy'), ('floral', 'Floral & Sweet'), ('fresh', 'Fresh & Citrus'), ('spicy', 'Spicy & Warm')], default='woody', max_length=50),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='therapy_goal',
            field=models.CharField(choices=[('stress', 'Stress Relief'), ('focus', 'Deep Focus'), ('meditation', 'Meditation'), ('cozy', 'Cozy Vibe')], default='cozy', max_length=50),
        ),
    ]
